language: node_js
node_js:
- '8'
sudo: required
cache: yarn
notifications:
  email: false
git:
  depth: 1
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- sudo apt-get install -y python3-pip
- pip3 install --user awscli
script:
- bash ./scripts/prepare-deploy.sh
- cat ~/.aws/credentials
- bash ./scripts/deploy.sh
# - yarn build
# - if [[ -d out && $TRAVIS_BRANCH == "master" ]]; then bash ./scripts/deploy.sh; fi;
