language: node_js
node_js:
  - "8"
sudo: required
cache: yarn
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: out
  repo: patternfly/patternfly.github.io
  target_branch: master
  verbose: true
  on:
    branch: gatsby2
git:
  depth: 1
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install
script:
  - travis_wait yarn build