language: node_js
node_js:
  - "8"
sudo: required
cache: yarn
notifications:
  email: false
git:
  depth: 1
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn install
script:
- travis_wait yarn build
