language: node_js
node_js:
  - "8"
sudo: required
cache: yarn
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: packages/patternfly-3/_site
  repo: https://github.com/jschuler/jschuler.github.io.git
  target_branch: master
  verbose: true
  on:
    branch: master
git:
  depth: 1
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install
script:
  - travis_wait yarn build